[package]
name = "pixels_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_particle_physics_2d = { path = "../engine_2d/" }
winit = "0.26.1"
pixels = "0.9.0"
